[project]
name = "ham-ibp-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docutils==0.22.2",
    "pefile==2024.8.26",
    "pyside6>=6.10.0",
]
